name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master , develop]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: subosito/flutter-action@v1.5.3

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
