name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master , develop]

jobs:
  build:
    runs-on: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
